<fieldset>
	<legend>Frequenciadia</legend>
	<ul>
		<li><label>Idfrequenciadia:</label><?php print $frequenciadia->getIdfrequenciadia(); ?></li>
		<li><label>Data:</label><?php print $frequenciadia->getData(); ?></li>
		<li><label>Presenca:</label><?php print $frequenciadia->getPresenca(); ?></li>
		<li><label>Tipo:</label><?php print $frequenciadia->getTipo(); ?></li>
		<li><label>Justificativa:</label><?php print $frequenciadia->getJustificativa(); ?></li>

	</ul>
</fieldset>