<fieldset>
	<legend>Reuniao</legend>
	<ul>
		<li><label>Idreuniao:</label><?php print $reuniao->getIdreuniao(); ?></li>
		<li><label>Comissao:</label><?php print $reuniao->getComissao(); ?></li>
		<li><label>Tiporeuniao:</label><?php print $reuniao->getTiporeuniao(); ?></li>
		<li><label>Data:</label><?php print $reuniao->getData(); ?></li>
		<li><label>Presenca:</label><?php print $reuniao->getPresenca(); ?></li>
		<li><label>Posto:</label><?php print $reuniao->getPosto(); ?></li>

	</ul>
</fieldset>