<form name="editDiscurso" id="editDiscurso" enctype="application/x-www-form-urlencoded" method="post">
	<fieldset>
		<legend>Edit Discurso</legend>
        <ul>
        	<li>
        		<label>Iddiscurso:</label>
        		<input id='iddiscurso' name='iddiscurso' type='text' placeholder='' value='<?php print $discurso->getIddiscurso(); ?>' required>
        	</li>
        	<li>
        		<label>Data:</label>
        		<input id='data' name='data' type='text' placeholder='' value='<?php print $discurso->getData(); ?>' required>
        	</li>
        	<li>
        		<label>Sessao:</label>
        		<input id='sessao' name='sessao' type='text' placeholder='' value='<?php print $discurso->getSessao(); ?>' required>
        	</li>
        	<li>
        		<label>Fase:</label>
        		<input id='fase' name='fase' type='text' placeholder='' value='<?php print $discurso->getFase(); ?>' required>
        	</li>
        	<li>
        		<label>Hora:</label>
        		<input id='hora' name='hora' type='text' placeholder='' value='<?php print $discurso->getHora(); ?>' required>
        	</li>
        	<li>
        		<label>Sumario:</label>
        		<input id='sumario' name='sumario' type='text' placeholder='' value='<?php print $discurso->getSumario(); ?>' required>
        	</li>

        </ul>
        <input type="submit" name="save" id="save" value="Save">
    </fieldset>
</form>