<h2>Automatic</h2>
<div>
Automatic is a code generator, artifact generator, prototype generator, or X generator, like you want and use.<br>
This generator uses database informations, patterns and personal configuration to generate artifacts more closer as possible to the final application, but its target to, dont generate excessive code.<br>
Automatic is mainly used to:
<ul>
<li>code to crud systems;</li>
<li>medium systems;</li>
<li>complex data enters</li>
<li>prototypes</li>
<li>...</li>
</ul>


<h3>History</h3>
Classgenerator...

</div>