<form name="project-new-form" id="newProj" enctype="application/x-www-form-urlencoded" method="post">
	<fieldset>
		<legend>General Configuration</legend>
        <ul>
        	<li>
        		<label>Driver:</label>
        		<input id=driver name=driver type=text placeholder="Doctrine Driver" value="<?php print $this->driver?>" required autofocus>
        	</li>
        	<li>
        		<label>Host:</label>
        		<input id=host name=host type=text placeholder="Host" value="<?php print $this->host?>" required>
        	</li>
        	<li>
        		<label>DB User:</label>
        		<input id=user name=user type=text placeholder="Database User" value="<?php print $this->user?>">
        	</li>
        	<li>
        		<label>DB Password:</label>
        		<input id=password name=password type=password value="<?php print $this->pass?>">
        	</li>
        </ul>
        <input type="submit" name="project-save" id="project-save" value="Save">
    </fieldset>
</form>