<form id="howto">
    <h3>How It Works</h3>
    <fieldset>
    	<legend>Create and Save Project</legend>
    	<ol>
    		<li>Put the basic information (host,database,user,pass).</li>
    	</ol>
    </fieldset>
    <fieldset>
    	<legend>Validate General Information</legend>
    	<ol>
    		<li>View and validate database informations.</li>
    	</ol>
    </fieldset>
    <fieldset>
    	<legend>Generate</legend>
    	<ol>
    		<li>Just do it.</li>
    	</ol>
    </fieldset>
    <fieldset>
    	<legend>Copy Artifacts</legend>
    	<ol>
    		<li>See the generated artifacts in automatic/application/projects</li>
    	</ol>
    </fieldset>
</div>