<div id="projects-list"></div>
<div id="projects-actions"></div>
<div id="projects-conteiner"></div>
<script type="text/javascript">
<!--
$('body').ready(function(){
	$.get('<?php print BASE_URL;?>project/list'	 , '', function(data){$("#projects-list").html(data);}, 'html');
	$.get('<?php print BASE_URL;?>project/actions' , '', function(data){$("#projects-actions").html(data);}, 'html');
});
//-->
</script>