<?php

namespace Mapper;

use Doctrine\ORM\EntityRepository;

/**
 * BaseMapper
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseMapper extends EntityRepository
{
}