<?php

namespace Mapper;

/**
 * Contract
 *
 * This class was generated by the Automatic PHP code generator. Add your own custom
 * repository methods below.
 */
class Contract extends BaseMapper
{
}