<?php

namespace Mapper;

/**
 * Customer
 *
 * This class was generated by the Automatic PHP code generator. Add your own custom
 * repository methods below.
 */
class Customer extends BaseMapper
{
}