<?php

namespace Mapper;

/**
 * Movement
 *
 * This class was generated by the Automatic PHP code generator. Add your own custom
 * repository methods below.
 */
class Movement extends BaseMapper
{
}