<?php

namespace Mapper;

/**
 * Participant
 *
 * This class was generated by the Automatic PHP code generator. Add your own custom
 * repository methods below.
 */
class Participant extends BaseMapper
{
}