<?php

namespace Mapper;

/**
 * Participantrole
 *
 * This class was generated by the Automatic PHP code generator. Add your own custom
 * repository methods below.
 */
class Participantrole extends BaseMapper
{
}