<?php

namespace Mapper;

/**
 * Province
 *
 * This class was generated by the Automatic PHP code generator. Add your own custom
 * repository methods below.
 */
class Province extends BaseMapper
{
}