		<h2>Discurso</h2>
		<table>
			<thead>
				<tr>
					<th>Iddiscurso</th>
					<th>Data</th>
					<th>Sessao</th>
					<th>Fase</th>
					<th>Hora</th>
					<th>Sumario</th>

					<th>View</th>
					<th>Edit</th>
					<th>Del</th>
				</tr>
			</thead>
			<tbody>
			<?php
			foreach($this->listDiscurso as $<class>):
			?>
				<tr>
					<td><?php print $discurso->getIddiscurso(); ?></td>
					<td><?php print $discurso->getData(); ?></td>
					<td><?php print $discurso->getSessao(); ?></td>
					<td><?php print $discurso->getFase(); ?></td>
					<td><?php print $discurso->getHora(); ?></td>
					<td><?php print $discurso->getSumario(); ?></td>
					
					<td>
						<a href="<class>/view/id/<?php print $<class>->getId;?>">
							<img src="public/images/bt_view.jpg"/>
						</a>
					</td>
					<td>
						<a href="<class>/edit/id/<?php print $<class>->getId;?>">
							<img src="public/images/bt_ed.jpg"/>
						</a>
					</td>
					<td>
						<a href="<class>/del/id/<?php print $<class>->getId();?>">
							<img src="public/images/bt_del.jpg"/>
						</a>
					</td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
		<div class="paginator">
			<?php
				if (isset($this->listDiscurso))
					print $this->paginationControl($this->listDiscurso, "All", "component/paginator.phtml");
			?>
		</div><!--end paginator-->