<fieldset>
	<legend>Discurso</legend>
	<ul>
		<li><label>Iddiscurso:</label><?php print $discurso->getIddiscurso(); ?></li>
		<li><label>Data:</label><?php print $discurso->getData(); ?></li>
		<li><label>Sessao:</label><?php print $discurso->getSessao(); ?></li>
		<li><label>Fase:</label><?php print $discurso->getFase(); ?></li>
		<li><label>Hora:</label><?php print $discurso->getHora(); ?></li>
		<li><label>Sumario:</label><?php print $discurso->getSumario(); ?></li>

	</ul>
</fieldset>