<form name="editVotacao" id="editVotacao" enctype="application/x-www-form-urlencoded" method="post">
	<fieldset>
		<legend>Edit Votacao</legend>
        <ul>
            <li>
                <label>Idvotacao:</label>
                <input id='idvotacao' name='idvotacao' type='text' placeholder='' value='<?php print $votacao->getIdvotacao(); ?>' required>
            </li>
            <li>
                <label>Data:</label>
                <input id='data' name='data' type='text' placeholder='' value='<?php print $votacao->getData(); ?>' required>
            </li>
            <li>
                <label>Sessao:</label>
                <input id='sessao' name='sessao' type='text' placeholder='' value='<?php print $votacao->getSessao(); ?>' required>
            </li>
            <li>
                <label>Projeto:</label>
                <input id='projeto' name='projeto' type='text' placeholder='' value='<?php print $votacao->getProjeto(); ?>' required>
            </li>
            <li>
                <label>Voto:</label>
                <input id='voto' name='voto' type='text' placeholder='' value='<?php print $votacao->getVoto(); ?>' required>
            </li>

        </ul>
        <input type="submit" name="save" id="save" value="Save">
    </fieldset>
</form>