<fieldset>
	<legend>Votacao</legend>
	<ul>
		<li><label>Idvotacao:</label><?php print $votacao->getIdvotacao(); ?></li>
		<li><label>Data:</label><?php print $votacao->getData(); ?></li>
		<li><label>Sessao:</label><?php print $votacao->getSessao(); ?></li>
		<li><label>Projeto:</label><?php print $votacao->getProjeto(); ?></li>
		<li><label>Voto:</label><?php print $votacao->getVoto(); ?></li>

	</ul>
</fieldset>