		<h2>Relatoria</h2>
		<table>
			<thead>
				<tr>
					<th>Idrelatoria</th>
					<th>Numero</th>
					<th>Orgao</th>
					<th>Situacao</th>
					<th>Autor</th>
					<th>Ementa</th>
					<th>Despacho</th>

					<th>View</th>
					<th>Edit</th>
					<th>Del</th>
				</tr>
			</thead>
			<tbody>
			<?php
			foreach($this->listRelatoria as $<class>):
			?>
				<tr>
					<td><?php print $relatoria->getIdrelatoria(); ?></td>
					<td><?php print $relatoria->getNumero(); ?></td>
					<td><?php print $relatoria->getOrgao(); ?></td>
					<td><?php print $relatoria->getSituacao(); ?></td>
					<td><?php print $relatoria->getAutor(); ?></td>
					<td><?php print $relatoria->getEmenta(); ?></td>
					<td><?php print $relatoria->getDespacho(); ?></td>
					
					<td>
						<a href="<class>/view/id/<?php print $<class>->getId;?>">
							<img src="public/images/bt_view.jpg"/>
						</a>
					</td>
					<td>
						<a href="<class>/edit/id/<?php print $<class>->getId;?>">
							<img src="public/images/bt_ed.jpg"/>
						</a>
					</td>
					<td>
						<a href="<class>/del/id/<?php print $<class>->getId();?>">
							<img src="public/images/bt_del.jpg"/>
						</a>
					</td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
		<div class="paginator">
			<?php
				if (isset($this->listRelatoria))
					print $this->paginationControl($this->listRelatoria, "All", "component/paginator.phtml");
			?>
		</div><!--end paginator-->