<form name="editDeputado" id="editDeputado" enctype="application/x-www-form-urlencoded" method="post">
	<fieldset>
		<legend>Edit Deputado</legend>
        <ul>
            <li>
                <label>Iddeputado:</label>
                <input id='iddeputado' name='iddeputado' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Matricula:</label>
                <input id='matricula' name='matricula' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Name:</label>
                <input id='name' name='name' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Partido:</label>
                <input id='partido' name='partido' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Estado:</label>
                <input id='estado' name='estado' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Pk:</label>
                <input id='pk' name='pk' type='text' placeholder='' value='' required>
            </li>

        </ul>
        <input type="submit" name="save" id="save" value="Save">
    </fieldset>
</form>