<form name="editFrequenciavotacao" id="editFrequenciavotacao" enctype="application/x-www-form-urlencoded" method="post">
	<fieldset>
		<legend>Edit Frequenciavotacao</legend>
        <ul>
        	<li>
        		<label>Idfrequenciavotacao:</label>
        		<input id='idfrequenciavotacao' name='idfrequenciavotacao' type='text' placeholder='' value='' required>
        	</li>
        	<li>
        		<label>Data:</label>
        		<input id='data' name='data' type='text' placeholder='' value='' required>
        	</li>
        	<li>
        		<label>Presenca:</label>
        		<input id='presenca' name='presenca' type='text' placeholder='' value='' required>
        	</li>
        	<li>
        		<label>Tipo:</label>
        		<input id='tipo' name='tipo' type='text' placeholder='' value='' required>
        	</li>

        </ul>
        <input type="submit" name="save" id="save" value="Save">
    </fieldset>
</form>