<fieldset>
	<legend>Proposicao</legend>
	<ul>
		<li><label>Idproposicao:</label><?php print $proposicao->getIdproposicao(); ?></li>
		<li><label>Numero:</label><?php print $proposicao->getNumero(); ?></li>
		<li><label>Orgao:</label><?php print $proposicao->getOrgao(); ?></li>
		<li><label>Situacao:</label><?php print $proposicao->getSituacao(); ?></li>
		<li><label>Data:</label><?php print $proposicao->getData(); ?></li>
		<li><label>Ementa:</label><?php print $proposicao->getEmenta(); ?></li>
		<li><label>Despacho:</label><?php print $proposicao->getDespacho(); ?></li>

	</ul>
</fieldset>