<form name="editReuniao" id="editReuniao" enctype="application/x-www-form-urlencoded" method="post">
	<fieldset>
		<legend>Edit Reuniao</legend>
        <ul>
            <li>
                <label>Idreuniao:</label>
                <input id='idreuniao' name='idreuniao' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Comissao:</label>
                <input id='comissao' name='comissao' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Tiporeuniao:</label>
                <input id='tiporeuniao' name='tiporeuniao' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Data:</label>
                <input id='data' name='data' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Presenca:</label>
                <input id='presenca' name='presenca' type='text' placeholder='' value='' required>
            </li>
            <li>
                <label>Posto:</label>
                <input id='posto' name='posto' type='text' placeholder='' value='' required>
            </li>

        </ul>
        <input type="submit" name="save" id="save" value="Save">
    </fieldset>
</form>