<fieldset>
	<legend>Relatoria</legend>
	<ul>
		<li><label>Idrelatoria:</label><?php print $relatoria->getIdrelatoria(); ?></li>
		<li><label>Numero:</label><?php print $relatoria->getNumero(); ?></li>
		<li><label>Orgao:</label><?php print $relatoria->getOrgao(); ?></li>
		<li><label>Situacao:</label><?php print $relatoria->getSituacao(); ?></li>
		<li><label>Autor:</label><?php print $relatoria->getAutor(); ?></li>
		<li><label>Ementa:</label><?php print $relatoria->getEmenta(); ?></li>
		<li><label>Despacho:</label><?php print $relatoria->getDespacho(); ?></li>

	</ul>
</fieldset>