<?php

namespace Mapper;

use Doctrine\ORM\EntityRepository;

/**
 * BaseMapper
 *
 * This class was generated by the automatic php code generator.
 */
class BaseMapper extends EntityRepository
{
    public function insert($entity)
    {
        $this->_em->persist($entity);
    }
    
    public function update($entity)
    {
        $this->_em->persist($entity);
    }
    
    public function save()
    {
        $this->_em->flush();
    }
}