<fieldset>
	<legend>Frequenciavotacao</legend>
	<ul>
		<li><label>Idfrequenciavotacao:</label><?php print $frequenciavotacao->getIdfrequenciavotacao(); ?></li>
		<li><label>Data:</label><?php print $frequenciavotacao->getData(); ?></li>
		<li><label>Presenca:</label><?php print $frequenciavotacao->getPresenca(); ?></li>
		<li><label>Tipo:</label><?php print $frequenciavotacao->getTipo(); ?></li>

	</ul>
</fieldset>