<form name="editFrequenciadia" id="editFrequenciadia" enctype="application/x-www-form-urlencoded" method="post">
	<fieldset>
		<legend>Edit Frequenciadia</legend>
        <ul>
        	<li>
        		<label>Idfrequenciadia:</label>
        		<input id='idfrequenciadia' name='idfrequenciadia' type='text' placeholder='' value='<?php print $frequenciadia->getIdfrequenciadia(); ?>' required>
        	</li>
        	<li>
        		<label>Data:</label>
        		<input id='data' name='data' type='text' placeholder='' value='<?php print $frequenciadia->getData(); ?>' required>
        	</li>
        	<li>
        		<label>Presenca:</label>
        		<input id='presenca' name='presenca' type='text' placeholder='' value='<?php print $frequenciadia->getPresenca(); ?>' required>
        	</li>
        	<li>
        		<label>Tipo:</label>
        		<input id='tipo' name='tipo' type='text' placeholder='' value='<?php print $frequenciadia->getTipo(); ?>' required>
        	</li>
        	<li>
        		<label>Justificativa:</label>
        		<input id='justificativa' name='justificativa' type='text' placeholder='' value='<?php print $frequenciadia->getJustificativa(); ?>' required>
        	</li>

        </ul>
        <input type="submit" name="save" id="save" value="Save">
    </fieldset>
</form>