<form name="project-new-form" id="newProj" enctype="application/x-www-form-urlencoded" action="post">
	<fieldset>
		<legend>New Project</legend>
        <ul>
        	<li>
        		<label>Name:</label>
        		<input id=name name=name type=text placeholder="Project_Name" required autofocus>
        	</li>
        	<li>
        		<label>Database Name:</label>
        		<input id=dbname name=dbname type=text placeholder="Database" required>
        	</li>
        	<li>
        		<label>Database User:</label>
        		<input id=user name=user type=text placeholder="Database User" value="<?php print $this->user?>" required>
        	</li>
        	<li>
        		<label>DB Password:</label>
        		<input id=password name=password type=password value="<?php print $this->pass?>" required>
        	</li>
        </ul>
        <input type="button" name="project-save" id="project-save" value="Save">
    </fieldset>
</form>
<script type="text/javascript">
<!--
$('#project-save').click(function(){
	$.post('<?php print BASE_URL;?>project/save', $('#newProj').serialize(), function(data){$("#projects-conteiner").html(data);}, 'html');
});
//-->
</script>