<form name="project-new-form" id="newProj" enctype="application/x-www-form-urlencoded">
	<fieldset>
		<legend>New Project</legend>
        <ul>
        	<li>
        		<label>Name:</label>
        		<input id=name name=name type=text placeholder="Project_Name" required autofocus>
        	</li>
        	<li>
        		<label>Database Name:</label>
        		<input id=dbname name=dbname type=text placeholder="Database" required>
        	</li>
        	<li>
        		<label>Database User:</label>
        		<input id=user name=user type=text placeholder="Database User" required>
        	</li>
        	<li>
        		<label>DB Password:</label>
        		<input id=password name=password type=password required>
        	</li>
        	<li>
        		<input type="button" name="project-create" id="project-create" value="Create">
        	</li>
        </ul>
    </fieldset>
</form>
<script type="text/javascript">
<!--
$('#project-create').click(function(){
	$.post('<?php print BASE_URL;?>project/create', $('#newProj').serialize(), function(data){$("#projects-conteiner").html(data);}, 'html');
});
//-->
</script>