<fieldset>
	<legend>Deputado</legend>
	<ul>
		<li><label>Iddeputado:</label><?php print $deputado->getIddeputado(); ?></li>
		<li><label>Matricula:</label><?php print $deputado->getMatricula(); ?></li>
		<li><label>Name:</label><?php print $deputado->getName(); ?></li>
		<li><label>Partido:</label><?php print $deputado->getPartido(); ?></li>
		<li><label>Estado:</label><?php print $deputado->getEstado(); ?></li>
		<li><label>Pk:</label><?php print $deputado->getPk(); ?></li>

	</ul>
</fieldset>