		<h2>Frequenciavotacao</h2>
		<table>
			<thead>
				<tr>
					<th>Idfrequenciavotacao</th>
					<th>Data</th>
					<th>Presenca</th>
					<th>Tipo</th>

					<th>View</th>
					<th>Edit</th>
					<th>Del</th>
				</tr>
			</thead>
			<tbody>
			<?php
			foreach($this->listFrequenciavotacao as $<class>):
			?>
				<tr>
					<td><?php print $frequenciavotacao->getIdfrequenciavotacao(); ?></td>
					<td><?php print $frequenciavotacao->getData(); ?></td>
					<td><?php print $frequenciavotacao->getPresenca(); ?></td>
					<td><?php print $frequenciavotacao->getTipo(); ?></td>
					
					<td>
						<a href="<class>/view/id/<?php print $<class>->getId;?>">
							<img src="public/images/bt_view.jpg"/>
						</a>
					</td>
					<td>
						<a href="<class>/edit/id/<?php print $<class>->getId;?>">
							<img src="public/images/bt_ed.jpg"/>
						</a>
					</td>
					<td>
						<a href="<class>/del/id/<?php print $<class>->getId();?>">
							<img src="public/images/bt_del.jpg"/>
						</a>
					</td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
		<div class="paginator">
			<?php
				if (isset($this->listFrequenciavotacao))
					print $this->paginationControl($this->listFrequenciavotacao, "All", "component/paginator.phtml");
			?>
		</div><!--end paginator-->